### PR TITLE
Source code not building on travis

### PR DESCRIPTION
**Pull request by sjmackenzie**
This PR originated from the 7th NDN International hackathon, our project was to create racket binding to this ndn-cpp. We noticed that missing dependencies (protobuf and zlib) caused the project to fail in the most obscure of ways, chewing 1/2 of our time. 

This PR ensures that 1) travis builds on every PR 2) all deps are present 3) it builds the actual source code and not just the docs.

### CODE REVIEW

**Comment by yoursunny** [comment]
COMMIT_MSG should indicate what is changed, as a verb phrase in present tense. It shouldn’t look like a bug title. See https://github.com/named-data/NFD/blob/master/CONTRIBUTING.md for guidelines.

Also, can you trigger Travis CI on your fork, and post the result link?

**Comment by jefft0** [comment]
@cawka Alex, you created this config file. Does this pull request look good to you?

**Comment by yoursunny** [comment]
> Regarding the "build on PR" it's standard convention to build every PR and it's good "devops" practice.
Yes.
> Why do you want contributors to setup a fork and see if it runs when travis is meant to do this ... that's what a continuous integration system is designed for.
Normally a contributor does not need to setup CI, but this is a special case: your CI script isn’t running in this repository, and I cannot effectively review this PR before seeing CI results.

**Review by yoursunny — CHANGES_REQUESTED** [review]
Need COMMIT_MSG correction and CI results.

**Comment by sjmackenzie** [comment]
Well the CI script never ran before because it was calling `make doxygen-doc` which isn't the actual project.

**Comment by sjmackenzie** [comment]
commit message is changed

**Review by yoursunny — APPROVED** [review]

**Pull request merged**
